# Generated by Django 3.2.5 on 2022-04-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
