# Generated by Django 3.2.5 on 2022-04-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk_api', '0005_alter_issue_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('F', 'Faible'), ('M', 'Moyenne'), ('E', 'Elevee')], max_length=5),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('CUR', 'Current'), ('DONE', 'Done')], max_length=5),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('BUG', 'Bug'), ('AC', 'Amelioration'), ('TASK', 'Tache')], max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('BACK', 'Backend'), ('FRONT', 'Frontend'), ('IOS', 'Ios'), ('AND', 'Android')], max_length=5),
        ),
    ]
