# Generated by Django 3.2.5 on 2022-04-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk_api', '0008_auto_20220424_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='project_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
