# Generated by Django 3.2.5 on 2022-04-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk_api', '0009_auto_20220424_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='user_id',
        ),
    ]
