# Generated by Django 3.2.5 on 2022-04-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk_api', '0010_remove_contributor_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='project_id',
            field=models.CharField(max_length=100),
        ),
    ]
