# Generated by Django 3.2.5 on 2022-04-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk_api', '0011_alter_contributor_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='user_id',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contributor',
            name='project_id',
            field=models.IntegerField(),
        ),
    ]
