# Generated by Django 3.2.5 on 2022-04-25 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk_api', '0017_alter_contributor_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='role',
        ),
        migrations.AlterField(
            model_name='issue',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='softdesk_api.project'),
        ),
    ]
